# Generated by Django 3.0.3 on 2020-03-02 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authservice', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='signup_at',
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.IntegerField(default=1, verbose_name=[(0, 'Doctor'), (1, 'Assistant'), (2, 'Patient')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
    ]
