# Generated by Django 3.0.3 on 2020-03-02 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authservice', '0003_auto_20200302_1136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.IntegerField(default=1, verbose_name=[(0, 'Doctor'), (1, 'Assistant'), (2, 'Client')]),
        ),
    ]
