# Generated by Django 3.0.3 on 2020-03-01 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authservice', '0001_initial'),
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='email',
        ),
        migrations.RemoveField(
            model_name='client',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='client',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='client',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='client',
            name='user',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='authservice.User'),
        ),
        migrations.RemoveField(
            model_name='client',
            name='records',
        ),
        migrations.AddField(
            model_name='client',
            name='records',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='client.Record'),
        ),
        migrations.DeleteModel(
            name='ClientRecord',
        ),
    ]
