# Generated by Django 3.0.3 on 2020-03-01 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authservice', '0001_initial'),
        ('client', '0002_auto_20200301_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='records',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.Record'),
        ),
        migrations.AlterField(
            model_name='client',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='authservice.User'),
        ),
    ]
