# Generated by Django 3.0.3 on 2020-03-02 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_auto_20200301_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='records',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='client.Record'),
        ),
    ]
