# Generated by Django 3.0.2 on 2020-02-29 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date_removed', models.DateTimeField(blank=True, null=True)),
                ('probable_start_time', models.DateTimeField()),
                ('actual_start_time', models.DateTimeField()),
                ('actual_end_time', models.DateTimeField()),
                ('status', models.IntegerField(choices=[(0, 'Created'), (1, 'Active'), (2, 'Cancelled')])),
                ('appointment_date', models.DateTimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
