# Generated by Django 3.0.3 on 2020-03-03 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='doc_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
