# Generated by Django 3.0.3 on 2020-03-04 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0004_auto_20200303_0729'),
        ('appointment', '0002_auto_20200303_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='appointment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appointment.Appointment'),
        ),
        migrations.CreateModel(
            name='DoctorShareRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date_removed', models.DateTimeField(blank=True, null=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.Doctor')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointment.Record')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
