# Generated by Django 3.0.3 on 2020-03-04 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
        ('appointment', '0003_auto_20200304_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorsharerecord',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='client.Client'),
        ),
    ]
