# Generated by Django 3.0.3 on 2020-03-04 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
        ('appointment', '0004_doctorsharerecord_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorsharerecord',
            name='client',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='client.Client'),
            preserve_default=False,
        ),
    ]
