# Generated by Django 3.0.3 on 2020-03-06 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0002_auto_20200303_0746'),
        ('appointment', '0006_record_is_revoked'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='assistant',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='assistant.Assistant'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feedback',
            name='is_anonymous',
            field=models.BooleanField(default=False),
        ),
    ]
