# Generated by Django 3.0.2 on 2020-02-29 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assistant', '0001_initial'),
        ('doctor', '0003_auto_20200229_1439'),
    ]

    operations = [
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date_removed', models.DateTimeField(blank=True, null=True)),
                ('time_slot_per_client_in_minutes', models.IntegerField()),
                ('first_consultation_fee', models.DecimalField(decimal_places=6, max_digits=20)),
                ('follow_up_consultation_fee', models.DecimalField(decimal_places=6, max_digits=20)),
                ('street_address', models.CharField(max_length=300)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('zip', models.IntegerField()),
                ('assistant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assistant.Assistant')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.Doctor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OfficeInsurance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date_removed', models.DateTimeField(blank=True, null=True)),
                ('insurance_name', models.CharField(max_length=255)),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='office.Office')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OfficeDoctorAvailability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date_removed', models.DateTimeField(blank=True, null=True)),
                ('day_of_week', models.IntegerField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('is_available', models.BooleanField()),
                ('reason_of_unavailability', models.CharField(max_length=255)),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='office.Office')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
