# Generated by Django 3.0.3 on 2020-03-03 05:43

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('office', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date_removed', models.DateTimeField(blank=True, null=True)),
                ('professional_statement', models.CharField(blank=True, max_length=300, null=True)),
                ('practicing_from', models.DateTimeField(blank=True, null=True)),
                ('consultation_fee', models.DecimalField(decimal_places=6, max_digits=20)),
                ('avg_consultation_time', models.DurationField(default=datetime.timedelta(seconds=1800))),
                ('specialization', models.CharField(max_length=255)),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='office.Office')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date_removed', models.DateTimeField(blank=True, null=True)),
                ('specialization_name', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DoctorAvailability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date_removed', models.DateTimeField(blank=True, null=True)),
                ('day_of_week', models.IntegerField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.Doctor')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
