# Generated by Django 3.0.2 on 2020-02-29 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='date_of_birth',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='practicing_from',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='procurement_year',
            field=models.DateTimeField(),
        ),
    ]
