# Generated by Django 3.0.3 on 2020-03-02 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0005_auto_20200301_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='specializations',
            field=models.ManyToManyField(blank=True, through='doctor.DoctorSpecialization', to='doctor.Specialization'),
        ),
    ]
