# Generated by Django 3.0.3 on 2020-03-15 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0007_auto_20200315_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctoravailability',
            name='end_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='doctoravailability',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
